Gdata:
  legend: 'Data'
  marker-size: 0.6

Gttll:
  fill-color: '#660000'
  legend: 't#bar{t}(ll)'

Gttllbin0:
  fill-color: '#cc0000'
  legend: 't#bar{t}(ll) Bin0'

Gttllbin1:
  fill-color: '#660000'
  legend: 't#bar{t}(ll) Bin1'

Gttllbin2:
  fill-color: '#996666'
  legend: 't#bar{t}(ll) Bin2'

Gttllbin3:
  fill-color: '#ff99cc'
  legend: 't#bar{t}(ll) Bin3'

Gttllbin4:
  fill-color: '#ff33cc'
  legend: 't#bar{t}(ll) Bin4'

Gttllbin5:
  fill-color: '#ff00ff'
  legend: 't#bar{t}(ll) Bin5'

Gttllbin6:
  fill-color: '#990099'
  legend: 't#bar{t}(ll) Bin6'

Gttllbin7:
  fill-color: '#996699'
  legend: 't#bar{t}(ll) Bin7'

Gttllbin8:
  fill-color: '#9933ff'
  legend: 't#bar{t}(ll) Bin8'

Gttllbin9:
  fill-color: '#ff9933'
  legend: 't#bar{t}(ll) Bin9'

Gttllbin10:
  fill-color: '#cc6633'
  legend: 't#bar{t}(ll) Bin10'

Gttllbin11:
  fill-color: '#ffcc33'
  legend: 't#bar{t}(ll) Bin11'

Gttllbin12:
  fill-color: '#cccc00'
  legend: 't#bar{t}(ll) Bin12'

Gttllbin13:
  fill-color: '#00cccc'
  legend: 't#bar{t}(ll) Bin13'

Gttllbin14:
  fill-color: '#006666'
  legend: 't#bar{t}(ll) Bin14'

Gttllbin15:
  fill-color: '#3399ff'
  legend: 't#bar{t}(ll) Bin15'

Gttllbin16:
  fill-color: '#33ccff'
  legend: 't#bar{t}(ll) Bin16'

Gttbkg:
  fill-color: '#666699'
  legend: 't#bar{t} others'

Gst:
  fill-color: '#333366'
  legend: 'Single top'

Gdy:
  fill-color: '#669966'
  legend: 'Z+Jets'

Gother:
  fill-color: '#666666'
  legend: 'Other'

