'combined_InclusiveBTag_InclusiveNJet_NEvents':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  sort-by-yields: true
  rename:
    - {from: 'combined_InclusiveBTag_InclusiveNJet_NEvents', to: 'll_InclusiveBTag_InclusiveNJet_NEvents_yield'}
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 0
  yields-title: '$\ell\ell$, $\textrm{N}_{\textrm{b-jet}} \geq 0$, $\textrm{N}_{\textrm{jet}} \geq 0$'

'combined_InclusiveBTag_GreaterOneJet_NEvents':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  sort-by-yields: true
  rename:
    - {from: 'combined_InclusiveBTag_GreaterOneJet_NEvents', to: 'll_InclusiveBTag_GreaterOneJet_NEvents_yield'}
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 1
  yields-title: '$\ell\ell$, $\textrm{N}_{\textrm{b-jet}} \geq 0$, $\textrm{N}_{\textrm{jet}} \geq 2$'

'combined_TwoBTag_GreaterOneJet_NEvents':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  sort-by-yields: true
  rename:
    - {from: 'combined_TwoBTag_GreaterOneJet_NEvents', to: 'll_TwoBTag_GreaterOneJet_NEvents_yield'}
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 2
  yields-title: '$\ell\ell$, $\textrm{N}_{\textrm{b-jet}} = 2$, $\textrm{N}_{\textrm{jet}} \geq 2$'

'combined_GreaterOneBTag_GreaterOneJet_NEvents':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  sort-by-yields: true
  rename:
    - {from: 'combined_GreaterOneBTag_GreaterOneJet_NEvents', to: 'll_GreaterOneBTag_GreaterOneJet_NEvents_yield'}
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 3
  yields-title: '$\ell\ell$, $\textrm{N}_{\textrm{b-jet}} \geq 2$, $\textrm{N}_{\textrm{jet}} \geq 2$'


