'data_obs.root':
  type: data
  pretty-name: 'Data'
  group: Gdata

'ttbarsignal.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttll
  yields-group: '1t#bar{t}(ll)'
  order: 9

'ttbarbgFromDilepton.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t} (not dileptonic)'
  order: 7

'ttbarbgFromLjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t} (not dileptonic)'
  order: 6

#'ttbarbgFromHadronic.root':
#  type: mc
#  cross-section: 1.0
#  generated-events: 1.0
#  group: Gttbkg
#  yields-group: '2t#bar{t} (not dileptonic)'
#  order: 5

'singletop.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gst
  yields-group: '3Single top'
  order: 4

'dy.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gdy
  yields-group: '4Z+jets'
  order: 8

'ttbarX.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 3

'diboson.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 2

'wjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 1

