GData:
  legend: 'Data'
  marker-size: 0.6

Gttll:
  fill-color: '#ee4444'
  legend: 'TTLL'

Gttlj:
  fill-color: '#990000'
  legend: 'TTLJ'

Gttjj:
  fill-color: '#330000'
  legend: 'TTHad'

GttV:
  fill-color: '#ff66ff'
  legend: 'ttV/H'

GZJets:
  fill-color: '#000099'
  legend: 'ZJets'

GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'

GSingleT:
  fill-color: '#990099'
  legend: 'ST'

GVV:
  fill-color: '#00cccc'
  legend: 'VV'

GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'

GLFVSTcs:
  line-color: '#99CC66'
  legend: 'STLFVc_s'

GLFVSTcv:
  line-color: '#99CC66'
  legend: 'STLFVc_v'

GLFVSTct:
  line-color: '#99CC66'
  legend: 'STLFVc_t'

GLFVSTus:
  line-color: '#6B8551'
  legend: 'STLFVu_s'

GLFVSTuv:
  line-color: '#6B8551'
  legend: 'STLFVu_v'

GLFVSTut:
  line-color: '#6B8551'
  legend: 'STLFVu_t'

GLFVTTcs:
  line-color: '#908DCC'
  legend: 'TTLFVc_s'

GLFVTTcv:
  line-color: '#908DCC'
  legend: 'TTLFVc_v'

GLFVTTct:
  line-color: '#908DCC'
  legend: 'TTLFVc_t'

GLFVTTus:
  line-color: '#4F4D80'
  legend: 'TTLFVu_s'

GLFVTTuv:
  line-color: '#4F4D80'
  legend: 'TTLFVu_v'

GLFVTTut:
  line-color: '#4F4D80'
  legend: 'TTLFVu_t'

#############
#  postfit  #
#############

Gtt:
  fill-color: '#ee4444'
  legend: 'TT'

# resue ST colors
GLFVcs:
  line-color: '#99CC66'
  legend: 'LFVc_s'

GLFVcv:
  line-color: '#99CC66'
  legend: 'LFVc_v'

GLFVct:
  line-color: '#99CC66'
  legend: 'LFVc_t'

GLFVus:
  line-color: '#6B8551'
  legend: 'LFVu_s'

GLFVuv:
  line-color: '#6B8551'
  legend: 'LFVu_v'

GLFVut:
  line-color: '#6B8551'
  legend: 'LFVu_t'

#As we never show QCD, reuse color
Gother:
  fill-color: '#d0cfd4'
  legend: 'Other'
