'h_dnn_pred_S5':
  x-axis: "DNN score"
  y-axis: "Events"
  y-axis-format: "%1% / bin"
  log-y: true
  log-x: true
  sort-by-yields: true
  save-extensions: ['pdf','png']
  for-yields: true
  yields-table-order: 0
  yields-title: 'DNN'
  ratio-y-axis-range: [0.01, 2]
  ratio-y-axis-auto-range: false
  signal-normalize-data: false
# log-x: true
#  rebin: 4
#  labels:
#    - {text: 'b2j3', position: [0.781, 0.806], size: 18}

