'h_chi2_S5':
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_mass_S5':
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_S5':
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_notoppt_S5':
  save-extensions: ['pdf', 'png']

'h_chi2_SMW_mass_S5':
  save-extensions: ['pdf', 'png']
