'DNN':
  x-axis: "DNN score"
  y-axis: "Events"
  y-axis-format: "%1% / bin"
  log-y: true
  log-x: true
  sort-by-yields: true
  save-extensions: ['pdf','png']
  for-yields: true
  yields-table-order: 0
  yields-title: 'DNN'
  ratio-y-axis-range: [0.7, 1.3]
  ratio-y-axis-auto-range: true
  #signal-normalize-data: false
  #labels:
  #  - {text: 'ct', position: [0.2, 0.806], size: 18, font: 44}
